### ISSUE TITLE
what about punished for server caused DC

### ISSUE THREAD

**Issue by ghost** [falsechicken/AntiCombatLog#1]
I have compiled your source and plan to use this on my server. However, I'm worried about lag caused disconnects. How does this plugin take that into account? I dont want players that are hurt then the server does a mass disconnect and those get punished for it.

**Comment by ghost** [comment]
Does this take into account of Alt+F4 loggers as well?

**Comment by ghost** [comment]
Ok punishment works, you get message on injury, you also get message upon reconnect, gear is dropped not sure at disconnect or reconnect, however global announcement of battle logger doesn't get shown.

**Comment by falsechicken** [comment]
It currently doesn't take lag disconnects into account at all. If you get disconnected for any reason and you have been damaged you will he reported as a combat logger. 

I cannot think of a way to differentiate between the types of disconnect. They all fire the same event. So I really have no way of knowing how they disconnect.

I'll look into the announcements later today. Thanks for testing. 

You can get my builds including bleeding edge stuff here: http://chickensbuilds.no-ip.biz:8080

**Comment by ghost** [comment]
Ok cool I will look at these :) That's fine. Maybe a way to check ping at disconnect or at damage taken? Say if its over like 350-400 then it may be due to DC

**Comment by falsechicken** [comment]
Yeah. I'll look into putting in some sort of lag protection.

**Comment by falsechicken** [comment]
I am going to close this issue and open a new one with a more concise report. 

Closed in favor of #3 #4 .
