### ISSUE TITLE
no save on automatic restart

### ISSUE THREAD

**Issue by FireBallBunny** [falsechicken/AntiCombatLog#7]
when this plugin triggers i have had reports that people building structures and other things have those objects disappear when the server comes back up.

**Comment by falsechicken** [comment]
Maybe fixed by dde1a95611fab2d930c46119df14e270ae0dd7d4?

**Comment by falsechicken** [comment]
Wait this is the wrong plug-in! xD.

Please follow up here: https://github.com/falsechicken/AutoShutdown2/issues/1
